Repository pyOpenSci/python-package-guide, pull requests merged in 2024-08, with the labels that each got.

#353 docs: preparing the Translation Files for Japanese
  locales/ja/LC_MESSAGES/CONTRIBUTING.po
  locales/ja/LC_MESSAGES/TRANSLATING.po
  locales/ja/LC_MESSAGES/documentation.po
  locales/ja/LC_MESSAGES/index.po
  locales/ja/LC_MESSAGES/package-structure-code.po
  locales/ja/LC_MESSAGES/tests.po
  locales/ja/LC_MESSAGES/tutorials.po
  noxfile.py
Labels: translations

#326 Add Spanish translation of parts of the Documentation section
  documentation/hosting-tools/sphinx-python-package-documentation-tools.md
  locales/es/LC_MESSAGES/documentation.po
Labels: translations

#331 docs: translate to Spanish python-package-structure.md file
  locales/es/LC_MESSAGES/package-structure-code.po
Labels: translations, lang-ES

#382 docs: add star-history to README
  README.md
Labels: documentation

#362 docs: delete duplicate content in a sentence
  TRANSLATING.md
Labels: documentation

#389 docs: fix the Unicode apostrophe issue in markdown files
  package-structure-code/python-package-distribution-files-sdist-wheel.md
  tutorials/installable-code.md
  tutorials/pyproject-toml.md
Labels: documentation

#385 docs: fix typos GitHub action -> GitHub Actions
  TRANSLATING.md
  package-structure-code/python-package-versions.md
  tests/index.md
  tests/tests-ci.md
  tests/write-tests.md
  tutorials/publish-pypi.md
Labels: documentation

#342 Translate tutorials page [partial/wip]
  locales/es/LC_MESSAGES/tutorials.po
Labels: translations, lang-ES

#372 docs: translate to Japanese index.md
  locales/ja/LC_MESSAGES/index.po
Labels: translations, lang-JA

#392 docs: drop "vanilla of" from sentence
  documentation/hosting-tools/myst-markdown-rst-doc-syntax.md
Labels: documentation

#387 docs: set Bot configuration `contributorsSortAlphabetically` True
  .all-contributorsrc
Labels: maintenance

#211 Add command line reference guide to the Tutorials page
  index.md
  tutorials/command-line-reference.md
  tutorials/intro.md
Labels: 🚀 ready-for-review, sprintable

#393 maint: ungoofy the header at intermediate widths
  _static/pyos.css
Labels: maintenance
