Repository pyOpenSci/python-package-guide, pull requests merged in 2024-09, with the labels that each got.

#333 docs: translate to Spanish python-package-build-tools.md
  locales/es/LC_MESSAGES/package-structure-code.po
Labels: translations, lang-ES

#407 docs: fix wrong word in section about conda repositories
  package-structure-code/publish-python-package-pypi-conda.md
Labels: documentation

#334 docs: translate to Spanish publish-python-package-pypi-conda.md
  locales/es/LC_MESSAGES/package-structure-code.po
Labels: translations, lang-ES

#337 docs: translating to Spanish complex-python-package-builds.md
  locales/es/LC_MESSAGES/package-structure-code.po
  package-structure-code/complex-python-package-builds.md
Labels: translations, lang-ES

#335 docs: translate to Spanish intro.md of package-structure-code
  locales/es/LC_MESSAGES/package-structure-code.po
Labels: translations, lang-ES

#411 docs: fix typo in documentation from Github to GitHub
  documentation/repository-files/intro.md
  index.md
  tutorials/publish-pypi.md
Labels: documentation

#398 docs: change update translation sessions in nox
  TRANSLATING.md
  noxfile.py
Labels: translations
